### ISSUE TITLE
Lags + How to use unsafe build with csx

### ISSUE THREAD

**Issue by gilsdav** [agracio/electron-edge-js#1]
Hello,
I have two questions that I hope you have the answer:
## Lags
JS
```
edge.func('nfc.csx')(command, (error, result) => {});
```
C#
```
public async Task<object> Invoke(int command)
{
    await Task.Run(() => {
        ...
    }
    ...
}
```
The main thread of the app freeze when I execute this. I reduce a litle the freeze time using Task.Run but it's realy tricky with a .net function that need to be called every 500ms.
### New informations
If I put the csx code in js using /* */, there is no freeze anymore
## Unsafe
When I try to put unsafe block in csx, it ask me to add /unsafe on compiler.
```
[DllImport(DLL_NAME, CallingConvention = CallingConvention.StdCall, CharSet = CharSet.Auto, EntryPoint = "GetReaderSerialNumber")]
public unsafe static extern DL_STATUS GetReaderSerialNumber(ulong* serial_number);
```
I need unsafe because the library was made like this.
I tried to put a project.json on the main path of my project but nothing changed.
```
{
    "buildOptions": {
        "allowUnsafe": true
    }
}
```

Thanks in advance for your help.

**Comment by agracio** [comment]
Hi,
How much of a lag are you experiencing? You should expect some lag as you basically using a complex wrapper around .NET call execution, and since you are using .csx files it would recompile them on every call.
I would suggest to wrap your C# calls in a .dll, this should both reduce lag and help you with the second problem as you can compile it with /unsafe flag.

**Comment by gilsdav** [comment]
Awesome! Thanks for your quick answer.
Everything works like a charm by generating dll with this compilation: `c:/Windows/Microsoft.NET/Framework/v4.0.30319/csc.exe /target:library nfc.cs /unsafe`

I have a last question : when I use electron-packager and I start the application I have 

> Cannot find module 'electron-edge-js'

Do I miss something ?

**Comment by agracio** [comment]
You need `electron-edge-js` in your node_modules. node_modules should be be at the same level as your package.json or part of `asar` archive.

**Comment by gilsdav** [comment]
Perfect !

I didn't care about dependency between js file of edge and the other files of the module.
I work with Angular and it take all needed js files on build (so we don't normally need node_modules anymore for production).

I deal with 2 package.json: one for Angular and one for Electron (copied on generated Angular build).

I need to put edge as dependencie in generated package.json
```
"dependencies": {
    "electron-edge-js": "^8.2.9"
}
```
And do an npm install for this file on every Angular build.
Packager can now copy this module and everything works.

Thanks very much for your explanations and your time.
