### ISSUE TITLE
Using electron-edge-js with self-contained DLLs

### ISSUE THREAD

**Issue by hambroz** [agracio/electron-edge-js#10]
Hi there,

I was able to successfully run the demo you made for .NET Core 2.0 interop. However, this has risen a question towards how to use self-contained .NET Core 2.0 DLLs. We really need to have a standalone, self-contained electron application and relying on .NET Core to be installed is not an option.

I can see some folders in the source tree related to this, so I tried to publish the DLL in the sample as self-contained, however it still used the shared .NET Core host.

Do you have any experience with this?

Many thanks,

Jan

**Comment by agracio** [comment]
Hi,
Both `edge-js` and `electron-edge-js` support standalone mode. Take a look at this recent issue for reference: https://github.com/agracio/edge-js/issues/24

**Comment by hambroz** [comment]
Hi there, thanks to the link you provided, I was able to make it work in the end. All the best, Jan
