### ISSUE TITLE
System.Drawing not supported on this platform

### ISSUE THREAD

**Issue by selvamM** [agracio/electron-edge-js#108]
We are converting an Electron application using Electron Edge & ASP NET MVC to Electron Edge & ASP NET CORE where we are facing an issue - **System.Drawing not supported on this platform**
![image](https://user-images.githubusercontent.com/6346856/106587356-86117b80-656f-11eb-978f-16599c418dfb.png)
It works fine with ASP Net MVC but same code throws error when used with ASP Net Core.
Our product based on drawing so system.drawing assembly cannot be skipped from referring.

Electron Edge

`
var getAppDomainDirectory = edge.func({

        assemblyFile: baseDll,

        typeName: localTypeName,

        methodName: 'GetAppDomainDirectory'
    });
`

ASP NET CORE

`
public async Task<object> GetAppDomainDirectory()
    {
    Image image1 = Image.FromFile(@"Capture.png");
    Image image2 = Image.FromFile(@"signature.jpg");
    PropertyItem propItem = image1.GetPropertyItem(20624);
    propItem.Id = 20625;
    image2.SetPropertyItem(propItem);
    return "";
    }
`

**Comment by selvamM** [comment]
Any updates on this issue?

**Comment by agracio** [comment]
It appears you have a problem with .NET Core, not with `edge-js`

**Comment by selvamM** [comment]
@agracio  I have raised query in asp net core forum
https://forums.asp.net/p/2174282/6331786.aspx?p=True&t=637483331195308745

**Comment by ArtS** [comment]
This is not electron-edge-js issue, this is your backend issue.

Needs to be closed.
