### ISSUE TITLE
electron 13

### ISSUE THREAD

**Issue by camhart** [agracio/electron-edge-js#115]
release for electron 13

**Comment by camhart** [comment]
PR up: https://github.com/agracio/electron-edge-js/pull/116

**Comment by camhart** [comment]
Since electron 13 uses the same version of node, I don't believe anything needs changed with this lib.  Closing issue.

**Comment by camhart** [comment]
Reopening--electron 13 does have issues with electron-edge-js.

**Comment by agracio** [comment]
Upgraded to support Electron v17
