### ISSUE TITLE
Unable to use on GNU linux (Ubuntu 20)

### ISSUE THREAD

**Issue by pmahend1** [agracio/electron-edge-js#118]
I am trying to use support [my VS Code extension for linux](https://github.com/pmahend1/PrettyXML/issues/64) as well, although installing dotnet and other dependencies and doing `electron-rebuild` when I call the `.node` file it gives me this error

`OSError: /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.29' not found (required by /home/user/.local/lib/..../libmonosgen.so.1...)`

My Ubuntu has Glibc 2.31 and 2.29 is no more available.

Could you please update build instructions for Linux?

**Comment by selvamM** [comment]
@pmahend1 Did you have any idea to resolve this issue? I have posted this 2 weeks ago still no updates.

https://github.com/agracio/electron-edge-js/issues/121

**Comment by pmahend1** [comment]
@selvamM No, I have not found a work-around. May be the source files of this repo need an update.
