### ISSUE TITLE
Uncaught error : Module did not self-register

### ISSUE THREAD

**Issue by MaheshwariMM** [agracio/electron-edge-js#123]
We are getting error - when we compile edge quick start in Linux environment

![image](https://user-images.githubusercontent.com/25785798/134131102-ec65b282-adce-44ff-a03b-0b5b6c19f2da.png)

**Comment by MaheshwariMM** [comment]
@agracio Could you please share us some solution to proceed?

**Comment by vedvratlodhi** [comment]
@MaheshwariMM  what is the version of electron you are using?
