### ISSUE TITLE
Support for Electron 15

### ISSUE THREAD

**Issue by HaraldStiwa** [agracio/electron-edge-js#125]
Electron version v15 has been released a few days ago:
https://www.electronjs.org/releases/stable

NodeJS Version v16.5.0:
https://www.npmjs.com/package/electron-releases

**Comment by togrady01** [comment]
Hi HaraldStiwa, by chance would you be willing to give a quick run through of how you rebuilt electron-edge-js for v15?

**Comment by HaraldStiwa** [comment]
Hello, I have executed the following in a MS Windows command prompt (from main directory):
`.\tools\build.bat release 15.0.0`
This command created the `lib\native\win32\15.0.0\` folder for me with the `edge_coreclr.node` and the `edge_nativeclr.node`  files inside it.

**Comment by agracio** [comment]
Upgraded to support Electron v17
