### ISSUE TITLE
Pre-compile for node.js version v9.8.0

### ISSUE THREAD

**Issue by ELCormier** [agracio/electron-edge-js#13]
I noticed you pre-compiled for node v9.8.0 17 days ago for [edge-js](https://github.com/agracio/edge-js/tree/master/lib/native/win32/x64) . I have a package that has electron-edge-js as a dependent, and was hoping to find out when you might be updating this project as well for v9.8.0 support. Thanks for your help, and for keeping this project alive.

**Comment by agracio** [comment]
`electron-edge-js` is only pre-compiled for Node.js versions that come bundled with Electron, any other version would not work with Electron. There is a list of Node.js version in the readme.

**Comment by ELCormier** [comment]
Thanks for the quick response. I'm currently using Node.js 9.8.0 and Electron 1.8.4 without any issues...

From my package.json:

  "dependencies": {
    "datatables.net-buttons-se": "^1.5.1",
    "datatables.net-se": "^1.10.16",
    "electron-edge-js": "^8.3.2",
    "jquery": "^3.3.1",
    "vue": "^2.5.16"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.44",
    "@babel/plugin-transform-runtime": "^7.0.0-beta.44",
    "@babel/preset-env": "^7.0.0-beta.44",
    "@babel/runtime": "^7.0.0-beta.44",
    "ajv": "^6.4.0",
    "babel-loader": "^8.0.0-beta.2",
    "css-loader": "^0.28.11",
    "electron": "^1.8.4",
    "file-loader": "^1.1.11",
    "less": "^2.7.3",
    "less-loader": "^4.1.0",
    "printer-dymo": "^1.0.1",
    "semantic-ui-less": "^2.3.1",
    "url-loader": "^1.0.1",
    "vue-hot-reload-api": "^2.3.0",
    "vue-html-loader": "^1.2.4",
    "vue-loader": "^14.2.2",
    "vue-style-loader": "^4.1.0",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^4.4.1",
    "webpack-cli": "^2.0.13",
    "webpack-dev-server": "^3.1.1"
  }

**Comment by agracio** [comment]
The version of Node.js that you have installed on your system is not used by Electron, it uses its own node.dll. Look in the folder that contains Electron.exe, right click on node.dll and you can see its version in Details tab.

**Comment by ELCormier** [comment]
You are absolutely correct, v8.2.1. Sorry for being a bonehead. Looks like my issue lies with webpack not pulling all the necessary resources, which is throwing my uncaught error trying to locate edge_nativeclr file. Thanks again for helping me narrow down the issue.

**Comment by agracio** [comment]
You cannot webpack `electron-edge-js` because it requires binary files, take a look at this comment for guidance https://github.com/agracio/edge-js/issues/16#issuecomment-354603476

**Comment by ELCormier** [comment]
Thanks again for saving me the headache, and pointing me in the right direction. Cheers!
