### ISSUE TITLE
Electron update to 19.x

### ISSUE THREAD

**Issue by GuoSirius** [agracio/electron-edge-js#134]
The electron has been updated to 19.x, but the package is still 13.x. Is it still under maintenance now? Is there any other update plan?

**Comment by GuoSirius** [comment]
> 
@Craigzyc Thank you very much, I also tried to build my own, but the build only supports the current system, not cross-platform

**Comment by agracio** [comment]
Merged https://github.com/agracio/electron-edge-js/pull/128 to support up to v17.

**Comment by agracio** [comment]
Added support for 19.x
