### ISSUE TITLE
The edge module has not been pre-compiled for Electron version 17.4.8 .

### ISSUE THREAD

**Issue by JoeABCDEF** [agracio/electron-edge-js#135]
node Version: 16.13.0;
electron Version: 17.4.8;

According to the version control information of markdown, there is still this problem

What version should I use

Is it okay to use vite esmodule?
![image](https://user-images.githubusercontent.com/39638510/175452083-0992dc68-0f20-4337-8a1c-18f02fe9cb3c.png)

**Comment by agracio** [comment]
Electron 17.x is supported.
