### ISSUE TITLE
edge.initializeClrFunc is not a function

### ISSUE THREAD

**Issue by BlakePeavy** [agracio/electron-edge-js#142]
Pulling down the quick start and I get an error inside the application "edge.initializeClrFunc is not a function"
I've ran npm -install and dotnet build. Did I forget something?

I've build the core libraries with .net 5 and 6, same outcome. Do I need to go back to even more out of date libraries?
Is there another issue at play?

**Comment by agracio** [comment]
Likely .NET 6 issue fixed with new release, please update `electron-edge-js-quick-start` and test again.

**Comment by BlakePeavy** [comment]
Looks to be working!
