### ISSUE TITLE
Please support electron22.

### ISSUE THREAD

**Issue by nasuadachi** [agracio/electron-edge-js#144]
I added "22.0.0" to tools\build.bat in my environment.
```
) else if "%3" equ "22.0.0" (
    SET target=16.17.1
```
Run it with powershell (administrator)
```
tools\build.bat release 22.0.0
```

Then, the downloaded node.exe shows the dialog "Cannot run on this PC" (Windows 10 22H2) and does not proceed.

I tried Windows 7 compatibility mode, but the result was the same.

This seems to be the end of my ability.

**Comment by agracio** [comment]
Released with support for Electron 20.x, 21.x and 22.x

**Comment by nasuadachi** [comment]
Thank you.
It was very helpful

ありがとうございます。
とても助かりました
