### ISSUE TITLE
Support for edge-ps

### ISSUE THREAD

**Issue by jackdh** [agracio/electron-edge-js#15]
Hey,

For powershell to work it required `edge-ps`https://github.com/dfinke/edge-ps.

It seems to break when installing it into the `app/package.json` folder. Has anyone else found a work around for this?

**Comment by agracio** [comment]
It probably an issue with electron builder, on a side note I have never heard of Edge.js working from asar archive it always fails to resolve dlls, let me know if thats not the case for you.

**Comment by jackdh** [comment]
Hey @agracio thanks for the quick reply, do you have any suggestions of how I might resolve this issue? Or do you think I should ask the question over at Electron Builder?

**Comment by agracio** [comment]
Since I don't have any experience working with electron builder I am not able to give any advise. Won't be surprised if you can't get any help from electron builder project though.
