### ISSUE TITLE
Can you review the requested commit for supporting electron v26?

### ISSUE THREAD

**Issue by bluaura** [agracio/electron-edge-js#154]
@agracio Can you review and merge a commit which is requested?
https://github.com/agracio/electron-edge-js/pull/153/commits/8b6f884ddb2d01b166fdb1471fa5dc766edaef30

**Comment by cloudpsn1993** [comment]
@bluaura You can change version and rebuild by yourself. Here is the version for electron ^v27.

https://github.com/cloudpsn1993/electron-edge-js

**Comment by agracio** [comment]
Completely missed notifications, merged and published
