### ISSUE TITLE
xlocale.h not found on Ubuntu while installing

### ISSUE THREAD

**Issue by vadi2** [agracio/electron-edge-js#16]
I'm having trouble installing this awesome module on Ubuntu 17.10:

```
vadi@volga:~/Programs/packager-demo$ rm -rf node_modules/electron-edge-js/
vadi@volga:~/Programs/packager-demo$ npm install

> electron-edge-js@8.3.2 install /home/vadi/Programs/packager-demo/node_modules/electron-edge-js
> node tools/install.js

make: Entering directory '/home/vadi/Programs/packager-demo/node_modules/electron-edge-js/build'
  TOUCH Release/obj.target/edge_nativeclr.stamp
  CXX(target) Release/obj.target/edge_coreclr/src/common/v8synchronizationcontext.o
  CXX(target) Release/obj.target/edge_coreclr/src/common/callbackhelper.o
  CXX(target) Release/obj.target/edge_coreclr/src/common/edge.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrembedding.o
In file included from ../src/CoreCLREmbedding/json/casablanca/include/cpprest/json.h:37:0,
                 from ../src/CoreCLREmbedding/coreclrembedding.cpp:8:
../src/CoreCLREmbedding/json/casablanca/include/cpprest/asyncrt_utils.h:44:10: fatal error: xlocale.h: No such file or directory
 #include <xlocale.h>
          ^~~~~~~~~~~
compilation terminated.
edge_coreclr.target.mk:120: recipe for target 'Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrembedding.o' failed
make: *** [Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrembedding.o] Error 1
```

I'm not sure which `xlocale.h` is it looking for? I already installed the dependencies necessary for the build (sans mono):

`curl g++ pkg-config libgdiplus libunwind8 libssl-dev make gettext libssl-dev libcurl4-openssl-dev zlib1g libicu-dev uuid-dev unzip`

**Comment by vadi2** [comment]
I've worked around it by doing `ln -s /usr/include/locale.h /usr/include/xlocale.h`.

**Comment by agracio** [comment]
I believe you need the following:
`apt-get install -y lsb-release apt-transport-https build-essential libssl-dev python` make sure you have all of those packages.

**Comment by HebaruSan** [comment]
Supposedly [xlocale.h was removed from glibc a while back](https://www.linuxquestions.org/questions/slackware-14/no-luck-with-libc-on-current-xlocale-h-missing-4175612648/).

If that `#include` is part of this project (too hard for me to tell), removing it might fix the issue.

**Comment by HebaruSan** [comment]
OK, here's the announcement of the removal of this file in August 2017:

https://sourceware.org/ml/libc-alpha/2017-08/msg00010.html

>* The nonstandard header <xlocale.h> has been removed.  Most programs should
>  use <locale.h> instead.  If you have a specific need for the definition of
>  locale_t with no other declarations, please contact
>  libc-alpha@sourceware.org and explain.

Would you accept a pull request implementing GNU's recommended solution of using locale.h instead?

**Comment by agracio** [comment]
Both `edge-js` and `electron-edge-js` with this PR have just been published to NPM. Please let me know if you have any problems.

**Comment by HebaruSan** [comment]
`npm install` now completes without errors on my system. Thanks for the new release!
