### ISSUE TITLE
create  electron-vite  ，run，fail

### ISSUE THREAD

**Issue by JianSheng60** [agracio/electron-edge-js#160]
![Q LM9KR_XG6DW%GV3D2ZPR](https://github.com/agracio/electron-edge-js/assets/86147523/4274651a-7966-4403-9a87-1aaa7f71bf4a)

Use the following command to install the project
yarn create @quick-start/electron

**Comment by agracio** [comment]
That does not explain anything about the issue you having. 
What is the problem with `electron-edge-js`, you showing some kind of error from VS using `yarn create @quick-start/electron` a command that is not related to this project.

**Comment by JianSheng60** [comment]
> That does not explain anything about the issue you having. What is the problem with `electron-edge-js`, you showing some kind of error from VS using `yarn create @quick-start/electron` a command that is not related to this project.

I used the following command
yarn create @quick-start/electron

created electron-vite template
 
can not work electron-edge-js

**Comment by agracio** [comment]
`yarn create @quick-start/electron` is not related to `electron-edge-js` if you have issues with ***quick-start/electron*** raise an issue in relevant repository.
