### ISSUE TITLE
Want to add 22 to this version

### ISSUE THREAD

**Issue by GuoSirius** [agracio/electron-edge-js#161]
22 is a transitional version that supports the last version of win 7. Can you consider rate maintenance

**Comment by agracio** [comment]
`electron-edge-js` uses specific Node.js version that is compatible with Electron release, it cannot be compiled with any other version of Node.js not even different minor version. You can see Electron specs here: https://releases.electronjs.org/

**Comment by agracio** [comment]
Does this answer your question? As mentioned above you can use Node.js 22, versions for pre-compiled binaries refer to Electron Node,js version.
