### ISSUE TITLE
Waiting for support Electron v30.2.x，node v20.15.0

### ISSUE THREAD

**Issue by oohusl** [agracio/electron-edge-js#162]

**Comment by agracio** [comment]
Added support for 30.2 and 31.1 with Node.js 20.15.0

**Comment by agracio** [comment]
30.3 is now on 20.15.1, 31 also has 21.15.1 merged waiting for release.
This is completely against their earlier policies where Node.js version was never updated after official release unless vulnerabilities were found.

**Comment by agracio** [comment]
30.3 and 31.3 released with Node.js 20.15.1
