### ISSUE TITLE
Packaged app throws an error "edge.initializeClrFunc is not a function"

### ISSUE THREAD

**Issue by aaarianme** [agracio/electron-edge-js#168]
Im packaging my electron app using electron-builder and when I ship this to other devices and run it, i get this error:
![thumbnail_image](https://github.com/user-attachments/assets/5ee913cb-c2b1-4fa7-ad54-0aeb19cf94eb)
 The error is in "myapp\dist\win-unpacked\resources\app\node_modules\electron-edge-js\lib\edge.js" file where it returns `edge.initializeClrFunc(options)`

I have tried building the app with `"asar":false` and `"asar": true` and I still get the same problem.

Can anyone help me troubleshoot this?

**Comment by agracio** [comment]
Did you take a look at packaging guides [Packaging Electron application](https://github.com/agracio/electron-edge-js#packaging-electron-application)?
`electron-edge-js` cannot be included in asar pack, you need to exclude it. If you getting the same error with both `"asar":false` and `"asar": true` then it is not excluded from asar archive.

**Comment by aaarianme** [comment]
Yeah I did. Should I manually change webpack.config as CRA doesn't let you customize it? 
I'm using create-react-app. In `package.json` I have:
```
  "build": {
    "extraResources": [
      {
        "from": "public/ExternalDLLs",
        "to": "extraResources",
        "filter": [
          "**/*"
        ]
      },
      {
        "from": "node_modules/electron-edge-js",
        "to": "node_modules/electron-edge-js",
        "filter": [
          "**/*"
        ]
      }
    ],
}
```
The ExternalDLLs folder contain my C# dlls.
My dist resources has this structure:
```
|   app-update.yml
|   app.asar
|   elevate.exe
|
+---app.asar.unpacked
|   \---node_modules
|       \---edge-cs
|           |   LICENSE
|           |   package.json
|           |
|           \---lib
|                   edge-cs-base.dll
|                   edge-cs-coreclr.deps.json
|                   edge-cs-coreclr.dll
|                   edge-cs.dll
|                   edge-cs.js
|
+---extraResources
|     ...... My C# dlls here
\---node_modules
    \---electron-edge-js
        ...... electron-edge-js files here
```

**Comment by agracio** [comment]
You do have `node_modules\electron-edge-js` however the error indicates that it is still trying to resolve electron-edge-js from asar archive.  
Unfortunately I am not familiar with create-react-app but assuming there must be some kind of a way to specify excluded modules similar to webpack etc.

**Comment by agracio** [comment]
Any progress?

**Comment by aaarianme** [comment]
I tried overriding webpack.config.js and the issue still persists. 
I am not setting process.env.EDGE_APP_ROOT anywhere explicitly.

I tried debugging the packaged app and I see in `electron-edge-js/src/edge.js` line 51 returns `true`:
```
if (process.versions['electron'] || process.versions['atom-shell'] || process.env.ELECTRON_RUN_AS_NODE) { // line 51
    edge = require(edgeNative); // line 52

}
```
but edge is a `{}` coming out of this condition. 
Not sure what is causing this. 

I'll take a look at the quick-start and try to troubleshoot this. Will post an update about that here soon.

**Comment by agracio** [comment]
Try creating a minimal GitHub repo that reproduces the error.

**Comment by aaarianme** [comment]
I just packaged the app on my test computer, and it works flawlessly on both the test computer and my personal device. Interestingly, after this packaging process, all previously packaged versions created on my personal device also run without any issues on the test computer.

I think we can narrow this down to some dependencies missing/not installed

I previously tried debugging the packaged app and I see in electron-edge-js/src/edge.js line 51 returns true:

```
if (process.versions['electron'] || process.versions['atom-shell'] || process.env.ELECTRON_RUN_AS_NODE) { // line 51
    edge = require(edgeNative); // line 52

}
```
but `edge `was a` {} `coming out of this condition.

Do you know what could be the issue?

**Comment by agracio** [comment]
I can only assume it was not finding the module in expected location but now it does.

**Comment by eug3** [comment]
I encountered this error as well when trying to ship the package to other devices

**Comment by eug3** [comment]
> I encountered this error as well when trying to ship the package to other devices

If it's the development machine, packaging, installation, and execution should not be a problem.

**Comment by eug3** [comment]
TypeError: edge.initializeClrFunc is not a function
    at exports.func (C:\**\app-2.2.36\resources\node_modules\electron-edge-js\lib\edge.js:177:17)

**Comment by agracio** [comment]
On dev machine C:**\app-2.2.36 works?

**Comment by eug3** [comment]
> On dev machine C:**\app-2.2.36\ works? 
> 
> What packager are you using?
> 
> On deployment machine try running it from cmd window it might give you additional errors in console.

Yes, C:/**/app-2.2.36 on the development machine, it works fine.Using an electron-forge for packaging. 
I'm debugging and hopefully finding the cause of the error.

**Comment by eug3** [comment]
> On dev machine C:**\app-2.2.36\ works? What packager are you using? On deployment machine try running it from cmd window it might give you additional errors in console.

I have enabled debugging, and many dynamic libraries are being loaded from `E:\user\.nuget\packages`. These libraries are not available on other devices.  
For example:  

```
EdgeAssemblyResolver::AddDependencies (CLR) - Added runtime assembly Humanizer.Core from E:\user\.nuget\packages\humanizer.core\2.14.1\lib\net6.0\humanizer.dll  
EdgeAssemblyResolver::AddDependencies (CLR) - Added supplementary runtime assembly Humanizer from E:\user\.nuget\packages\humanizer.core\2.14.1\lib\net6.0\humanizer.dll  
EdgeAssemblyResolver::AddDependencies (CLR) - Processing runtime dependency package Microsoft.CodeAnalysis  
EdgeAssemblyResolver::AddDependencies (CLR) - Added runtime assembly Microsoft.CodeAnalysis from E:\user\.nuget\packages\microsoft.codeanalysis.common\4.9.2\lib\net6.0\microsoft.codeanalysis.dll  
```

There are many other similar cases.

**Comment by agracio** [comment]
Do you have .NET SDK or .NET Runtime installed on deployment machine? What is the error that you see in console?

**Comment by eug3** [comment]
> Do you have .NET SDK or .NET Runtime installed on deployment machine? What is the error that you see in console? 
> 
> 
> 
> You project should have the following in .csproj file to copy all the required assemblies to output directory. 
> 
> ```xml
> 
> <PropertyGroup>
> 
>     <PreserveCompilationContext>true</PreserveCompilationContext>
> 
>     <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
> 
> <PropertyGroup/>
> 
> ```
> 
> 
> 
> Make sure to update to latest release of `electron-edge-js` and take a look at https://github.com/agracio/electron-edge-js-quick-start-forge
> 
> 
> 
> What kind of debug output you getting on deployment machine?
> 
> 
Is the electron-edge-js initial implementation is a failure, I gave the project a patch
tools/install.js 

`['publish', '--configuration', 'Release' , '-o' , './bin/Release'], `

The missing third-party dll is compiled into the release foThe problem of loading error can be resolved. My project is using net8.0, so I changed the target platform to net8.0. Now the project is running smoothly on other devices ^. ^✌️

**Comment by agracio** [comment]
Perfect

**Comment by aaarianme** [comment]
I made the same patch to `tools/install.js` but now I'm getting a different error:
`Error: The specefied module could not be found  C:/**/resources/node_modules/electron-edge-js/build/.../edge_coreclr.node`

I have my dlls along with the thir-party dlls my ptoject depends on all in one folder. That folder doesnt have any .net dlls included. Could that be issue?

**Comment by aaarianme** [comment]
this is the full path that is trying to require:
`"C:\**\resources\node_modules\electron-edge-js\build\Release\edge_coreclr.node"`
I can verify that this file exists. On the dev machine it runs fine. On the deployment machine it fails and says not found even though I just verified that it does exist

**Comment by agracio** [comment]
It will only look at `electron-edge-js/build` if for some reason it is generated, what OS are you running on dev/deploy?

**Comment by aaarianme** [comment]
Windows on both. 

I also made the same patch as @eug3 

> > I gave the project a patch.
> tools/install.js
> ['publish', '--configuration', 'Release' , '-o' , './bin/Release'],

**Comment by agracio** [comment]
You should not have `build` directory on Windows, it is not part of `electron-edge-js`, delete it

**Comment by aaarianme** [comment]
Still the same issue.
in `lib/edge.js` line 52 throws an error saying this path cannot be found:
`C:\**\resources\node_modules\electron-edge-js\lib\native\win32\x64\30.0.0\edge_coreclr`

This file does exist however

**Comment by agracio** [comment]
Did you try launching it terminal to see if there is more output in console?

**Comment by aaarianme** [comment]
Yes I did. No errors besides that.

This is the path its trying to resolve:
`\\?\C:\**\resources\node_modules\electron-edge-js\lib\native\win32\x64\30.0.0\edge_coreclr`

I'm not sure what the `\\?\` comes from. I even tried hard-coding the path to a copy of `edge_coreclr` on my desktop but it would still result in the same error, but with the desktop path

**Comment by aaarianme** [comment]
this is the code I have in place now:
```
if (process.versions['electron'] || process.versions['atom-shell'] || process.env.ELECTRON_RUN_AS_NODE) {
    edge = require("C:\\Users\\Owner\\Desktop\\edge_coreclr.node"); // instead of require(edgeNative)
}
```
and the same error persists

**Comment by agracio** [comment]
But the exact same package works on your dev PC correct?

**Comment by aaarianme** [comment]
Yes it does. its very weird

**Comment by aaarianme** [comment]
I finally fixed the path problem but I still get the original error:
```

TypeError: edge.initializeClrFunc is not a function
at exports.func (C:**\resources\node_modules\electron-edge-js\lib\edge.js:177:17)
```

**Comment by agracio** [comment]
And you did not specify `process.env.EDGE_APP_ROOT` on both dev and deployment PCs?

**Comment by eug3** [comment]
> I finally fixed the path problem but I still get the original error:
> 
> ```
> 
> 
> 
> TypeError: edge.initializeClrFunc is not a function
> 
> at exports.func (C:**\resources\node_modules\electron-edge-js\lib\edge.js:177:17)
> 
> ```
> 
> 
> 
> UPDATE----
> 
> 
> 
> The pathing issue is only with this specific file: `"edge_coreclr.node"`
> 
> 

My guess is that your installation package was updated to other devices over the network.
You can try uninstall the old one，And reinstall a new package.Perhaps we can solve this problem.

**Comment by aaarianme** [comment]
I will set `EDGE_DEBUG=1` and post an update here.

> My guess is that your installation package was updated to other devices over the network.
> You can try uninstall the old one，And reinstall a new package.Perhaps we can solve this problem.

I'm using`electron-builder`to package this app. I see in your previous comment that you used `electron-forge`. Are you referring to that?

**Comment by eug3** [comment]
> > And you did not specify process.env.EDGE_APP_ROOT on both dev and deployment PCs since incorrect path can cause the same error.
> 
> 
> 
> That's correct. I'm only setting `process.env.EDGE_USE_CORECLR = 1`
> 
> 
> 
> I will set `EDGE_DEBUG=1` and post an update here.
> 
> 
> 
> > My guess is that your installation package was updated to other devices over the network.
> 
> > You can try uninstall the old one，And reinstall a new package.Perhaps we can solve this problem.
> 
> 
> 
> I'm using`electron-builder`to package this app. I see in your previous comment that you used `electron-forge`. Are you referring to that? 

I previously encountered an issue with the Squirrel.Windows installer where the edge_coreclr.node path could not be found during automatic updates.
