### ISSUE TITLE
Packaging error

### ISSUE THREAD

**Issue by favour1025** [agracio/electron-edge-js#170]
![1734000299545](https://github.com/user-attachments/assets/6584f412-73fb-4fee-b877-419fe396a0ea)

**Comment by agracio** [comment]
Can you create a simple repo that reproduces the problem.

**Comment by agracio** [comment]
New release soon to remove this problem on Windows.

**Comment by agracio** [comment]
Update to v33.0.4

**Comment by favour1025** [comment]
> Can you create a simple repo that reproduces the problem.

Does this plugin require administrator privileges？？？

**Comment by agracio** [comment]
As I mentioned in previous comment update `electron-edge-js` in your package to v33.0.4. It removes powershell script.

**Comment by favour1025** [comment]
Thank you, the issue has been resolved

**Comment by favour1025** [comment]
> As I mentioned in previous comment update `electron-edge-js` in your package to v33.0.4. It removes powershell script.

Thank you, the issue has been resolved
