### ISSUE TITLE
Example and d.ts issues with typescript?

### ISSUE THREAD

**Issue by grofit** [agracio/electron-edge-js#18]
Just doing a quick spike using this and I noticed right away that the example on the front page implies that the `func` method should only take a single param (the method body) but the d.ts implies that you need to pass in `func("cs", methodBody)`.

However once you do this typescript (latest 2.8.3) you get an error:

`A parameter initializer is only allowed in a function or constructor implementation.`

Am I doing anything crazy here?
```ts
import * as edge from "electron-edge-js";

showOutput(){
            const helloWorld = edge.func("cs", `async (input) => {
                    return ".NET Welcomes " + input.ToString();
                }`);

            helloWorld("test", function (error, result) {
                if (error) throw error;
                console.log(result);
            });
        }
```

**Comment by agracio** [comment]
Looks like the same issue: https://github.com/agracio/edge-js/issues/36, I am guessing that something changed in Typescript that marks type definitions as error. I will look into it in the next few days.

**Comment by grofit** [comment]
You can fix it by changing it to:

```ts
function func<TInput, TOutput>(language: string, params: string | Function | Params | Source | TSQL) : Func<TInput, TOutput>;
```

The example could do with updating on the front page to also show you need to pass in "cs" as the first arg too.

**Comment by agracio** [comment]
You should not need to pass 'cs' as first parameter because its a default. The example is correct but type definitions need updating.

**Comment by trodi** [comment]
@agracio , typescript doesn't allow you to provide a default value inside a `d.ts` function definition. You can mark a param as optional, however this requires you to mark all following options as optional as well. Instead you must provide an additional function definition (aka, function overload).

If you want to signify that the first version has a "cs" default, you can add JSDoc to the `d.ts` file.

I'll submit a PR with this change.

```typescript
function func<TInput, TOutput>(params: string | Function | Params | Source | TSQL): Func<TInput, TOutput>
function func<TInput, TOutput>(language: string, params: string | Function | Params | Source | TSQL): Func<TInput, TOutput>
```

**Comment by agracio** [comment]
Merged PR, will be releasing new version over the weekend.

**Comment by agracio** [comment]
Released
