### ISSUE TITLE
Packaging for Windows from Mac or Linux

### ISSUE THREAD

**Issue by DionDavid** [agracio/electron-edge-js#20]
Hey Agracio,

My app is targeting different platforms, including Windows, Linux and macOS (both ia32 and x64) and modern Node versions. The app doesn't have any platform-specific behavior.

If I install the project's dependencies using npm install, electron-edge-js downloads binaries just for the current platform (let's say win32, x64, Node v8.1).

Could you maybe make your package node-pre-gyp ready? So I can create packages from any platform for any platform?

Yours Sincerely,

Dion David

**Comment by agracio** [comment]
You need to package it separately for each platform. The binaries included with `electron-edge-js` are are for all supported Node.js versions for Windows, there are no precompiled versions for Linux and macOS. On those platforms you need to run `npm install` to create the appropriate binaries.

**Comment by DionDavid** [comment]
Ah the problem is that I have to package for every platform from a linux environment. Do you know how I can achieve this integration regarding your package?

**Comment by agracio** [comment]
Don't know if that can be done. It's unlikely that a binary compiled on Linux will work on macOS.

**Comment by MatxBerg** [comment]
I also need to be able to build any platform from Linux. Libraries like drivelist, serialport and usb-detection do support pre built binary for most of the platforms which make it possible to build from any platform without having to compile at build.

Would it be possible to consider pre building binaries, at least for windows?

Example:
![image](https://user-images.githubusercontent.com/2973549/62413444-1e2a4f80-b5dd-11e9-9638-acf2f2d5c194.png)

**Comment by Hammster** [comment]
@MatxBerg There are prebuild binaries for Windows.

@agracio Though to touch this topic slightly, I think we should use a CI and `prebuild` to serve the built `.node` libraries for the relevant node and electron releases only. The biggest benefit is that we do make the package smaller by letting a script download the correct `.node` file via `prebuild` and also allow to build the whole application on any system.
