### ISSUE TITLE
undefined returned from call using result from edge.func()

### ISSUE THREAD

**Issue by FrederickBrier** [agracio/electron-edge-js#24]
My code is essentially the HelloWord example embedded in the extension.ts of a Visual Studio Code extension. My dev environment is Visual Studio Code, but I have Visual Studio Enterprise 2017 with almost all the optional modules installed.

**From extension.ts:**
```typescript
   var createHelloState = edge.func({
        source: path.join(__dirname, "..\\Startup.csx"),
        references: [path.join(__dirname, "..\\dlls\\TestState.dll")],
    });

    var helloState = createHelloState(__dirname);
```
**Startup.csx:**
```csharp
            using System;
            using System.Threading.Tasks;
            using TestState;
            
            public class Startup
            {
                public async Task<object> Invoke(string appDir)
                {
                    var helloState = new HelloState(appDir);
                    return new {
                        getName = (Func<object,Task<object>>)(
                            async (i) => 
                            { 
                                return helloState.GetName(); 
                            }
                        ),
                        setName = (Func<object,Task<object>>)(
                            async (newName) => 
                            { 
                                helloState.SetName((string)newName); 
                                return helloState.GetName();
                            }
                        )
                    };
                }
            }
```
After executing the edge.func() call, createHelloState has a value of "function (d, cb) { … }". However, calling createHelloState returns an undefined. electron-edge-js is version 8.3.6. node-gyp is version 3.7.0. node is v8.11.3. npm is version 5.6.0. Is there a way to debug into the C# from the typescript call? Is there anything obvious that I am doing wrong? Can you have silent failures in the code generated proxies between typescript and C# that would result in not returning the tuple of Func<> objects? How do you debug this?

**Comment by FrederickBrier** [comment]
The code is based on the edge sample [110_clr_instance.js](https://github.com/tjanczuk/edge/blob/master/samples/110_clr_instance.js). The main difference is that the Person class became a HelloState class with a getName()/setName(), and that it is running in a Visual Studio Code Electron instance.

**Comment by agracio** [comment]
I think you could debug a call into dll attaching VS debugger to VS Code maybe, not even sure. But have you tried starting with some very simple code and returning just 'hello world' from .csx file and making it more complex to figure what makes it break. Removing dll reference is a start.
