### ISSUE TITLE
.NET support for the library

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [agracio/electron-edge-js#27]
Hi
We are looking to work in .NET 4.6.1. I have noticed that the original project only mentions 4.5. Does this library support dlls made with .NET 4.6.1?
Thanks

**Comment by agracio** [comment]
Hi,
Yes it supports .NET 4.6.1

**Comment by SayakMukhopadhyay** [comment]
Great! Thanks for the quick reply. I will close this issue.
