### ISSUE TITLE
Marshaling Problem with properties in structs

### ISSUE THREAD

**Issue by peter-sabath** [agracio/electron-edge-js#29]
When there are structs (or classes which use them) and these structs use properties, the resulting object on the javascript side is corrupted. (fields work fine!) 
Values from those properties are mostly 0 but sometimes contain some "random" value. 
I never encountered a crash here from a possibly bad pointer.

This problem is only present with the mono implementation (on Mac, mono 5.4)

Using the following C# file
```
using System;
using System.Threading.Tasks;

namespace Test
{
	public struct Data
	{
		public int Value1;
		public int Value2;
		public int Value3 { get; set; }
		public int Value4 { get; set; }

		public Data(int aMult)
		{
		  Value1 = 1* aMult;
		  Value2 = 2* aMult;
		  Value3 = 3* aMult;
		  Value4 = 4* aMult;
		}
	}

	public class EdgeTest
	{
		public async Task<object> GetData(dynamic aInput)
		{
			return new Data(1);
		}
	}
}
```
with the (stripped) javascript code
```
const edge = require('electron-edge-js');

var clrMethod = edge.func({
    assemblyFile: 'EdgeTest.dll',
    typeName: 'Test.EdgeTest',
    methodName: 'GetData' // This must be Func<object,Task<object>>
});	

clrMethod(null, function (error, result) {
    if (error) throw error
    console.log(JSON.stringify(result))
});
```
outputs `{"Value1":1,"Value2":2,"Value3":0,"Value4":0}`

**Comment by agracio** [comment]
Unfortunately I will not be able to solve this problem.

**Comment by peter-sabath** [comment]
Tested the case on an barebone Windows based Mono embedding project and got the same unexpected behavior.

Filed an issue at the mono project: [https://github.com/mono/mono/issues/11068](url)
