### ISSUE TITLE
Can't load Core2 dll

### ISSUE THREAD

**Issue by ghstahl** [agracio/electron-edge-js#3]
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

</Project>

namespace Hello.Core
{
    public class Startup
    {
        public async Task<object> Invoke(object input)
        {
            return "Hello from dot net core 2";
        }
    }
}
```
The project is located [Here](https://github.com/ghstahl/electron-quick-start-core2)  with my [entry point](https://github.com/ghstahl/electron-quick-start-core2/blob/master/src/MEF/Hello.Core/Startup.cs)  

I am using the electron-quick-start project and added the following lines of code to [main.js](https://github.com/ghstahl/electron-quick-start-core2/blob/master/src/main.js)
```
  var helloWorld = edge.func({
    assemblyFile: path.join(__dirname, '\\MEF\\Hello.Core\\bin\\Debug\\netcoreapp2.0\\Hello.Core.dll'),
    typeName: 'Hello.Core.Startup'
  });
```
Trying to load "Hello.Core.dll" results in the following error;  

![net core electron edge js cant load](https://user-images.githubusercontent.com/201257/34062316-cf0c99ce-e1a0-11e7-92f2-bf5f08511005.png)

The electron version is;
```
Hello World!

We are using Node.js 7.9.0, Chromium 58.0.3029.110, and Electron 1.7.9.
```
I was hoping this would support .Net Core 2.

**Comment by agracio** [comment]
So what is the problem you encounter.
Please describe the actual error and a platform you use to test it.

**Comment by ghstahl** [comment]
updated the issue.

**Comment by agracio** [comment]
By default Edge.js will always try to use .NET Framework on Windows. You need to set a flag to instruct it to use .Net Core. Set `process.env.EDGE_USE_CORECLR=1` in your code before calling Edge.js.

**Comment by ghstahl** [comment]
That did it.
In my main.js I know have this;
```
const electron = require('electron')
process.env.EDGE_USE_CORECLR = 1;
var edge = require('electron-edge-js');
```

Thanks

**Comment by jmorrisIII** [comment]
I get the following error when I try the same thing.

![image](https://user-images.githubusercontent.com/7073531/36922525-c147e45a-1e2d-11e8-9637-463b6bc52433.png)

**Comment by agracio** [comment]
Can you give more details, are you using the same code, what .NET Core version you have installed?

**Comment by jmorrisIII** [comment]
I created a new .net core Class Library project in VS 2017. I am using .net core version 2.1.4. I created an identical project in regular .net and tried it with no problems. 
Thanks for your help.

.net core
```
using System.Threading.Tasks;

namespace Edge.Scanner
{
    public class StartUp
    {
        public async Task<object> TestScanner(dynamic input)
        {
            return await Task.Run(async () =>
            {
                return true;
            });
        }
    }
}
```
If I do not add `process.env.EDGE_USE_CORECLR = 1` I get the following error. If I do add that line of code I get the error I posted above.
![image](https://user-images.githubusercontent.com/7073531/37037241-7dec2ce2-2117-11e8-82f4-211bf5c1aa00.png)

**Comment by agracio** [comment]
Have you tried https://github.com/agracio/electron-edge-js-quick-start ?

**Comment by jmorrisIII** [comment]
I get the following error.
![image](https://user-images.githubusercontent.com/7073531/37038837-7b408c46-211b-11e8-9937-08ce888cf147.png)

**Comment by agracio** [comment]
Please create sample repo for me to take a look.

**Comment by agracio** [comment]
Do you get any errors during `npm install` ?

**Comment by jmorrisIII** [comment]
dotnet build

![image](https://user-images.githubusercontent.com/7073531/37039439-18d67ac8-211d-11e8-8313-c72ef5f0cf3c.png)

npm install
![image](https://user-images.githubusercontent.com/7073531/37039623-920908de-211d-11e8-845c-1a25f85ec222.png)

**Comment by agracio** [comment]
I am not able to replicate the problem on my local Windows 10 install, .NET Core 2.1.4

**Comment by jmorrisIII** [comment]
I'm on windows 7. Not sure that matters.

**Comment by jmorrisIII** [comment]
Do you think the problems are related? My project and the starter project?

**Comment by agracio** [comment]
Windows 7 .NET Core 1.1.0 - same error as yours.

**Comment by jmorrisIII** [comment]
No big deal. I will proceed using regular .net. The .net portion on my app is small. I was wanting to make it more mobile using core. If you figure out the issue I can easily convert it to .net core. 
Thanks again
