### ISSUE TITLE
Failed At System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)   

### ISSUE THREAD

**Issue by charlzyx** [agracio/electron-edge-js#31]
I Want to use this to develop With BarTender SDK

While i run the Demo in VS 2015, It Works Well;
When i copy the Demo in electron-edge-js, it works bad

here is Demo

```csx

        using System.Threading.Tasks;
        using Seagull.BarTender.Print;
    
        public class Startup
        {
            public async Task<object> Invoke(object input)
            {
                using (Engine btEngine = new Engine())

                {

                    // Application specific code 

                    // Explicitly start the engine 

                    btEngine.Start();

                    LabelFormatDocument format = btEngine.Documents.Open(@"C:\Users\Administrator\Desktop\BartenderTemplate\test.btw");
                    format.PrintSetup.IdenticalCopiesOfLabel = 1;
                    //format.PrintSetup.PrinterName = "TOSHIBA B-EX4T1 (203 dpi)";
                    format.PrintSetup.PrinterName = "Microsoft Print to PDF";
                    format.Print();

                // Application-specific code 

                // Assuming the application wants to save changes, 

                //it can be easily done at Stop time. 

                btEngine.Stop(SaveOptions.SaveChanges);
                    return 0;
                }
                return 0;
            }
        }
```

And Error at Here

message:"路径中具有非法字符。"
name:"System.ArgumentException"
StackTrace: 
```
"   At System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   At System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   At System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   At System.ComponentModel.Design.RuntimeLicenseContext.GetSavedLicenseKey(Type type, Assembly resourceAssembly)
   At System.ComponentModel.LicenseManager.LicenseInteropHelper.GetCurrentContextInfo(Int32& fDesignTime, IntPtr& bstrKey, RuntimeTypeHandle rth)
   At  Seagull.BarTender.Print.Engine.Start(EngineSettings engineSettings, LicenseKeyManaged license, IntPtr interactiveUserHandle)"
```

I know less about C#, but it seems that PermissionChecks Failed, I tried 
- change `electron.exe` `electron.exe.manifest` and repackaged by `mt.exe `
- run `electron.exe` by Admin Permisson Always use right click
 Unfortunately, all of them doesn't work;

Very Confused, need Help;

here is my package.json
```json
{
  "name": "electron-quick-start",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "repository": "https://github.com/electron/electron-quick-start",
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron": "^3.0.7"
  },
  "dependencies": {
    "electron-edge-js": "^10.11.0"
  }
}

```

here is my OS
![image](https://user-images.githubusercontent.com/18055018/49818404-92de1e80-fdad-11e8-8b7d-0cb4793d2eb7.png)

And node
```
C:\Users\Administrator>node -v
v10.2.0
```

**Comment by agracio** [comment]
Stack trace shows that it cannot open license, not sure how licensing works with that software.

**Comment by charlzyx** [comment]
> Stack trace shows that it cannot open license, not sure how licensing works with that software.

@agracio thanks for answers !
but why it work well at vs2015?  I had copied the App.Config form vs2015 project. I will back when i get somthing

**Comment by charlzyx** [comment]
@agracio I got it!

The Method `btEngine.Start()` need an `IntPtr parentWindow` from `HWND`, 

in native C# Code, it seems that can be got automatic  ; 

but  here i call C# by `electron-edge-js`,  can't got it automatic  , so i fixed it by manually specified

i get it by this api [win.getNativeWindowHandle()
](https://electronjs.org/docs/api/browser-window#wingetnativewindowhandle)

solution
- at `electron`
```js
const win = remote.getCurrentWindow();
const  hwnd = win.getNativeWindowHandle().readUInt32LE();   // node Buffer -> C# DWORD
```
- at `C#`

```csharp
IntPtr parentWindow = new IntPtr(hwnd);
```

Obviously, that is not `electron-edge-js`'s bug. i will close it;

anyway, thanks for you and `electron-edge-js`, very helpful for me!
