### ISSUE TITLE
TypeError: edge.initializeClrFunc is not a function (electron 2, 3)

### ISSUE THREAD

**Issue by ulmer-morozov** [agracio/electron-edge-js#33]
Hello, noble coders!

On my machine everything works like a charm, in development and even on production builds that i made with electron-packager and electron-builder. On my machine apps works fine on windows and macOS. But when i tried install or launch app from directory on different PC/Mac or clean virtual machine i got absolutely annoying edge error:

> polyfills.4f1f9ade919f8c9100b8.js:1 ERROR Error: Uncaught (in promise): TypeError: edge.initializeClrFunc is not a function
TypeError: edge.initializeClrFunc is not a function
    at Object.exports.func (C:\b\resources\app\node_modules\electron-edge-js\lib\edge.js:185:17)
    at new t (file:///C:/b/resources/app/dist/main.cd46168f267b484bf4ac.js:1:375289)

App uses dotnet core 2.2 with published win7-x64 runtime, electron 3 and latest electron-edge-js.
Few days i spend beating this error and i was defeated.

Initial app testing setup was clean Win 7 SP1 x64 on Virtual Box, but further i tried:

- enable/disable asar packing 
- install latest updates (on test OS)
- install nodejs and dotnet core 2.2 (on test OS)
- install visual studio with all c++ build libraries (on test OS)
- install different versions of microsoft c++ redistributable from 2010 til 2017, both x86 and x64 (on test OS).
- build edge_coreclr.node with --debug
- run dependency walker on my .exe
got those general dll load errors%
> API-MS-WIN-CORE-WINRT-ERROR-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ROBUFFER-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-STRING-L1-1-0.DLL
BLUETOOTHAPIS.DLL
DCOMP.DLL
IESHIMS.DLL
![virtualbox_win764_22_01_2019_12_58_19](https://user-images.githubusercontent.com/7135845/51528123-02ccd380-1e47-11e9-8dfc-c6e882e9de2a.png)

but every time i got same error.
Setting process.env.EDGE_DEBUG = 1 didn't help, because error is thrown before initialization of edge.js.

Appreciate any help or clues =)
P.S. @agracio thank you for your work, this library is the best electron-c# bridge i ever tried!

**Comment by montoyaaguirre** [comment]
I'm having the same issue. I'm working with another developer. Each of us can run a pack the application with no problems. The issue is that we can only run the package in our own systems.
