### ISSUE TITLE
will not find node-gyp installed in a different location

### ISSUE THREAD

**Issue by seiyria** [agracio/electron-edge-js#38]
It looks like it's hardcoded and doesn't attempt to even try to find node-gyp if it's not at this location: https://github.com/agracio/electron-edge-js/blob/master/tools/build.bat#L70

For nvm and other node management users, it's not here. Why not just try to run node-gyp directly?

**Comment by stereokai** [comment]
How do other projects do it?

**Comment by seiyria** [comment]
Honestly, at this point, you could just use `npx`. No reason to look for a hardcoded path.

**Comment by stereokai** [comment]
So how would you do it with `npx`? Also I don;t know much, but doesn't `windows-build-tools` replace `node-gyp` on Windows?

**Comment by seiyria** [comment]
`npx node-gyp --build...`

I'm not sure where the talk or relation to windows-build-tools came into place either; I have not mentioned them. That said:

Windows build tools only installs some SDKs and Python, which is needed by node-gyp. As you can see in the linked batch file used by this repo, gyp is still necessary for this process.
