### ISSUE TITLE
Can't load Core2 dll when it has a reference

### ISSUE THREAD

**Issue by ghstahl** [agracio/electron-edge-js#4]
The original issue (#3) of not being able to load an core2 dll was resolved by including the following;
```
process.env.EDGE_USE_CORECLR=1
```
in my main.js.  

I then created a new [ClassLibrary](https://github.com/ghstahl/electron-quick-start-core2/tree/master/src/MEF/Some.Library) that contained nothing but the following;
```
using System;

namespace Some.Library
{
    public class SomeClass
    {
        public DateTime GetDateTimeNow()
        {
            return DateTime.Now;
        }
    }
}
```
My [Hello.Core](https://github.com/ghstahl/electron-quick-start-core2/tree/master/src/MEF/Hello.Core) project references the new [Some.Library](https://github.com/ghstahl/electron-quick-start-core2/tree/master/src/MEF/Some.Library) project and uses the SomeClass as follows; 
```
public class Startup
    {
       // public CommandCompositionHelper CommandCompositionHelper { get; set; }

        public Startup()
        {

        }
        public async Task<object> Invoke(object input)
        {
            var dd = JsonConvert.SerializeObject("Hello from dot net core 2"); // Newtonsoft.Json.dll can be loaded.
            var pp = new SomeClass().GetDateTimeNow(); // can't load Some.Library.dll
            return dd + pp;
        }
    }
```
![can t load some libary](https://user-images.githubusercontent.com/201257/34083265-2d2bdfec-e322-11e7-8fb3-cf41fb7bc860.png)
```
Hello World!

We are using Node.js 7.9.0, Chromium 58.0.3029.110, and Electron 1.7.9.
```
It doesn't have a problem with Newtonsoft.Json.dll, which is not located in my bin folder.  So .net core is able to load it from somewhere.   However my personal helper library, Some.Library, can't be loaded.

I attached a debugger and saw that my Startup constructor is hit when I make the following call from main.js, which defers loading for my SomeLibrary.dll until its needed;
```
  var helloWorld = edge.func({
    assemblyFile: path.join(__dirname, '\\MEF\\Hello.Core\\bin\\Debug\\netcoreapp2.0\\Hello.Core.dll'),
    typeName: 'Hello.Core.Startup'
  });
```
When I make a call to; 
```
helloWorld({
      url: 'local://v1/programs/is-installed',
      method: 'GET',
      headers: {
          'Content-Type': 'application/json',
          'X-Symc-Fetch-App-Version': '1.0'
      },
      body: {
          displayName: 'Norton Internet Security'
      }
  }, function(error, result) {
      if (error) throw error;
      console.log(result);
  });
```
Some.Library.dll is then required and can't be loaded.

**Comment by ghstahl** [comment]
Thanks I will give this a go using the following addition to my csproj; 
```
<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
```
That unfortunately doesn't chase down all the children.  Only stuff at the top level like Newtonsoft.Json.dll.  As you suggested I will have to reference everything.   I know that asp.net core 2 lets me do something where it does chase all dependency resulting in a massive deploy package.

**Comment by agracio** [comment]
I dont really see a reason why you would want to copy all assemblies into the output folder. 
`<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` will only copy the additional referenced assemblies into the output folder, extra 11 dlls in my build when applied to Helo.Core project. The rest is part of the base .NET Core library and as long as .NET Core is installed on the target PC you dont need to copy anything else.

Step 6 is actually unnecessary as netcoreapp1.1 is compatible with 2.0 build, so you dont need to modify `electron-edge-js` package.

Step 7 is the one I forgot in my original post. You only need EdgeJs.dll, but instead of copying the dll it  would be easier if you reference it in your main .NET project and set `CopyAlways` property on it (`<Private>true</Private>`), ensuring that its copied to the correct output folder .

I have created a basic Electron + Edge.Js quickstart app for using .NET Core. It uses multiple dlls like in your example and manages dll local output appropriately. Take a look at both .NET projects definitions and `edge` usage. Note that `edge` is now used in `renderer.js`. 
https://github.com/agracio/electron-edge-js-quick-start

**Comment by ghstahl** [comment]
Well I guess you win 🥇 
I like your quickstart app a lot more than mine.
Works like a charm, and I added in calling out from main.js as well.

**Comment by PragmaticBeaver** [comment]
This may be a little off-topic but i think it fits pretty well;

I got a wrapper project (lets call it MyWrapper) to wrap the business logic of my application. Both are C#/CLR-Assemblies, the interesting part seems to be, that my businesslogic is a NuGet Package, lets call this one MyEngine.

The MyWrapper hast the following project definition:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MyEngine" Version="5.0.9" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.1" />
    <PackageReference Include="Microsoft.CodeAnalysis" Version="2.10.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.5.0" />
    <PackageReference Include="Microsoft.DotNet.InternalAbstractions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="EdgeJs">
      <HintPath>..\..\..\node_modules\electron-edge-js\lib\bootstrap\bin\Release\netcoreapp1.1\EdgeJs.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
```

The MyEngine package is a .Net Core 2.2 Package and references a few other NuGet's which are also .Net Core 2.2 NuGets. I distribut my application in one single folder using a script wich workes perfectly fine, it pretty much does the following:

`dotnet publish -c Release --framework netcoreapp2.2 --output "./../../../dist/cSharpWrapper/" -r win-x64 --self-contained true`

Every dll-file is present in the dist/cSharpWrapper-folder (.Net Core, edgejs, MyWrapper, MyEngine and the dependencies of MyEngine) but as soon as i start my project and it calls a edge.func, i get this Error:

(the censored assembly is the MyEngine-assembly)
![Unbenannt2](https://user-images.githubusercontent.com/8586904/55472942-9d971a80-560d-11e9-8184-e65d7a1e0e29.png)

And yes, i am using electron-edge-js in the main process.
I am also using the correct syntax for the C# -methods as well as for the edge.func's, jsut like to doc's said.

Can you tell me what I'm missing?

Greetings from germany!
