### ISSUE TITLE
Node 12 Heads Up

### ISSUE THREAD

**Issue by stereokai** [agracio/electron-edge-js#44]
@agracio 

Electron 5 will be released in 2 weeks, with Node 12 support:
https://electronjs.org/docs/tutorial/electron-timelines

In addition, Electron is transitioning into a faster release schedule, to keep up to date with latest Chromium:
https://electronjs.org/blog/electron-5-0-timeline

Which means in the foreseeable future, we will be seeing more and more Electron releases on top of Node 12, at an increased rate. Supporting Node 12 seems like an important step for future-proofing this great project.

How can I help? What needs to be done to get Node 12 support with edge-js and electron-edge-js?

**Comment by ksajay** [comment]
Yes Electron 5 is already out, and has some bug fixes that we also want to incorporate. I see that you have already incorporated Node 12 support for edge-js. Can you please advise when Node 12 support will be available for electron-edge?

**Comment by stereokai** [comment]
(Closed by accident)

@agracio Please address? Would love to help

**Comment by breuere** [comment]
@agracio I see that edge-js now has "[initial support for Node.js 12](https://github.com/agracio/edge-js/commit/a3e01ef95c27b6cc89bf0dcaaee60f774bf7f555)"
Any timeline on when that will make it over to here?

**Comment by agracio** [comment]
New version with Electron 5 support is out. Tested using https://github.com/agracio/electron-edge-js-quick-start.
