### ISSUE TITLE
Hello World is not working with electron 5 / node 12

### ISSUE THREAD

**Issue by ReOrg360** [agracio/electron-edge-js#47]
I have created a basic hello word example. It does not use any external dll. Just a basic inline .net statement. But if you do "npm start" it fails without any proper error message.

https://github.com/ReOrg360/test-electron-edge-js

Looks like it fails as we are NOT using EDGE_USE_CORECLR by using below line of code. While I think it should still work fine without EDGE_USE_CORECLR.

`process.env.EDGE_USE_CORECLR = 1;`

Please help. I am willing to help to fix it but need some pointers. :)

**Comment by ukenny** [comment]
Can you try setting creating the BrowserWindow in the `main.js` like this:

```mainWindow = new BrowserWindow({width: 1052, height: 600, webPreferences:{sandbox: false, nodeIntegration: true, nodeIntegrationInWorker: true}});```

That's only way I could get a .NET Framework project to run.

**Comment by Hammster** [comment]
That's the only way to get any native node module running in a render process with electron >= 5

**Comment by agracio** [comment]
New release fixes .NET Framework support for Electron 5.x and adds support for Electron 6.x.
