### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by aispark** [agracio/electron-edge-js#49]
Environments:

"electron-edge-js": "^12.0.1",
"electron": "^5.0.6",
"vue-cli-plugin-electron-builder": "^1.3.4",

Running:, vue-cli
Runtime: Node v10.16.1
Operating System: windows 64bit

Steps to reproduce:

node_modules/elcetron-edge-js/lib/edge.js
add console.log
![20190804_204753](https://user-images.githubusercontent.com/5924872/62423263-e36a0980-b6f9-11e9-9c85-f7f1b6340d6a.png)

vue-cli-service electron:serve --mode development
![20190804_204244](https://user-images.githubusercontent.com/5924872/62423205-56bf4b80-b6f9-11e9-90b6-850853a150e4.png)

next step
vue.config.js add configuration
![20190804_204333](https://user-images.githubusercontent.com/5924872/62423217-7ce4eb80-b6f9-11e9-8161-00bc795deaf6.png)

vue-cli-service electron:serve --mode development
![20190804_204023](https://user-images.githubusercontent.com/5924872/62423286-11e7e480-b6fa-11e9-830f-59552b262478.png)

repo: https://github.com/aispark/vuecli-electron-test

**Comment by midnight1994** [comment]
I also encountered this problem

**Comment by agracio** [comment]
Same issue as https://github.com/agracio/electron-edge-js/issues/57 and https://github.com/agracio/electron-edge-js/issues/54, please update to latest version.
