### ISSUE TITLE
Support for electron 6?

### ISSUE THREAD

**Issue by ReOrg360** [agracio/electron-edge-js#51]
First of all thanks for a wonderful library. Electron 6 has been released few days ago. Just wondering are there any plans to add support for Electron 6 to this library. Asking because the previous released library version does not work well with Electron 5 as mentioned in issue #47.

I am willing to help doing this task, but will need some pointers. Thanks!

**Comment by ukenny** [comment]
I got it working on electron 6.02. I just needed to change the electron version, remove node modules, run `npm i`, and `nodeIntegrationInWorker: true` to the `webPrefences` when instantiating the `BrowserWindow`. Here's a link to the [repo](https://github.com/ukenny/electron-edge-js-example).

**Comment by agracio** [comment]
New release fixes .NET Framework support for Electron 5.x and adds support for Electron 6.x.
