### ISSUE TITLE
DevTools empty (electron 5.0.9, node 10.16)

### ISSUE THREAD

**Issue by risikoruk** [agracio/electron-edge-js#53]
This is probably a dumb question but I am new to C# and I just can't get the example to work. I used the electron quick start project ( not the one from this electron-edge, the electron default one).

I added nodeIntegration to it, the added the following code to renderer.js

`var edge = require('electron-edge-js');

var helloWorld = edge.func(function () {/*
    async (input) => {
        return ".NET Welcomes " + input.ToString();
    }
*/});

helloWorld('JavaScript', function (error, result) {
    if (error) throw error;
    console.log(result);
});
`

Nothing else was added. It seems like when I start the program with npm start though, the DevTools console immediately gets disconnected and the App remains blank

Any idea why this doesn't work at all? I feel like I am missing something easy

**Comment by ukenny** [comment]
I had this happen to me when I wasn't setting the right `webPreferences` value when creating the `BrowserWindow`. I had to have add open the window like this:

 `mainWindow = new BrowserWindow({width: 1052, height: 600, webPreferences:{sandbox: false, nodeIntegration: true, nodeIntegrationInWorker: true}});`

**Comment by agracio** [comment]
Same issue as https://github.com/agracio/electron-edge-js/issues/57 and https://github.com/agracio/electron-edge-js/issues/54, please update to latest version.
