### ISSUE TITLE
Electron process gets aborted when using native clr version for Electron >=4.0

### ISSUE THREAD

**Issue by peter-sabath** [agracio/electron-edge-js#57]
This is no bug of electron-edge-js, but a big trap someone using it can run into.

When building the native CLR version in debug using Electron >= 4.0 what requires the use of the delayed load hook, there is a problem with node-gyp. They provide the file `win_delay_load_hook.cc` which is used for DLL redirection.

Unfortunately even the current latest version 5.0.3 is lacking an already commited fix [5736079](https://github.com/nodejs/node-gyp/commit/573607981e70dc5a28635676acc83afabe43317d)

Without it you might end up with an `abort` message from the windows loader, because the loader code gets enriched to initialize the framework which is a bad idea when executing this DLL-loader code.

Took me hours to sort out.

**Comment by andrearx** [comment]
Hi,
maybe it's the same problem of my issue #50 , how did you resolve?

**Comment by Hammster** [comment]
try to set the latest `node-gyp` version in your package.json if it's not there just add it

**Comment by andrearx** [comment]
@Hammster still having the same problem, I tried also to create a binding.gyp file but seems ignored or it isn't the right way

**Comment by peter-sabath** [comment]
@andrearx as I wrote the latest `node-gyp` version 5.0.3 does not come with the fix.
So you either should use our (temporary) `node-gyp` from at [ArticySoftware/node-gyp](https://github.com/ArticySoftware/node-gyp) or replace the file `src/win_delay_load_hook.cc` in your global installation of `node-gyp` until hopefully the 5.0.4 version will contain the fix.

**Comment by agracio** [comment]
@peter-sabath Could you give full steps for building Electron 4+ native dlls. If I use ArticySoftware/node-gyp can I use `build.bat` as is with `win_delay_load_hook=true`? Are there any additional steps like the ones mentioned in https://github.com/agracio/electron-edge-js/issues/32?

**Comment by andrearx** [comment]
@Hammster I replaced the file, next I create the `binding.gyp` file:
```
{
  "targets": [
  {
    "target_name": "addon",
    "sources": [ "aFolder/mydll.dll" ],
    "msbuild_settings": {
      "ClCompile": {
        "CompileAsManaged": "true",
        "ExceptionHandling": "Async",
      }
    }
  }]
}
```
and I set
```
webPreferences: {
      sandbox: false,
      nodeIntegration: true,
      nodeIntegrationInWorker: true
}
```
but the problem still persist.
Have you got any ideas?

**Comment by peter-sabath** [comment]
@agracio For my there are no other tasks required. The only trap I know is if you are building debug versions you need the proper VS runtime DLLs alongside of the Electron.exe file.
Unfortunately there is no VS runtime installer for those and it is not allowed to redist those DLLs. (`vsruntime140d.dll, ucrtbased.dll, msvcp140d.dll`)

**Comment by agracio** [comment]
Thanks @peter-sabath , I will attempt to recompile native versions of `electron-edge-js` over the weekend and commit changes after testing. Everyone please hang on, will try to get those changes in ASAP.

**Comment by agracio** [comment]
New version is now on NPM, fixed .NET Native support for Electron 5.0.x and added support for Electron 6.0.x
