### ISSUE TITLE
Problem when distributing electron-edge with electron-builder: edge-cs.dll not found

### ISSUE THREAD

**Issue by HaraldStiwa** [agracio/electron-edge-js#62]
Hello,
I have created a very simple demonstration repository at https://github.com/HaraldStiwa/electron-edge-js-with-electron-builder.git
In my main.js I invoke edge.func two times:

1. The first invocation uses C#.NET code embedded with template strings into the JS-code.
2. The second invocation calls a method stored in a separate .cs file.

When I now start `npm run electron` everything works correctly and I get the following expected output:
```
Hello World (from inlined code)!
log message 1
Hello World (from dotnet.cs code)!
log message 2
```

When I start `npm run build` (this will start electron-builder with `"asar": false`) and then execute the generated executable with e.g., `release\win-unpacked\electron-edge-js-with-electron-builder.exe` from MS windows, I get the same expected output.
My resources directory inside the relase directory of electron-builder looks like this:
![resources](https://user-images.githubusercontent.com/45351461/65768927-98390980-e132-11e9-96e7-33177025499d.jpg)

When I start `npm run build-with-asar` (this will start electron-builder with `"asar": true` - which is the default value -, bundle all node_modules except for edge-cs and electron-edge-js and the .js/.cs files into an app.asar file) and then execute the generated executable with e.g., `release-with-asar\win-unpacked\electron-edge-js-with-electron-builder.exe` from MS windows, I an error message *basically meaning it cannot find the file edge-cs.dll or a dependency of it*:
```
Error: Die Datei oder Assembly "file:///C:\workspace\electron-edge-js-with-electron-builder\release-with-asar\win-unpacked\resources\app.asar\node_modules\edge-cs\lib\edge-cs.dll" oder eine Abh├ñngigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
    at Object.exports.func (C:\workspace\electron-edge-js-with-electron-builder\release-with-asar\win-unpacked\resources\app.asar\node_modules\electron-edge-js\lib\edge.js:187:17)
    at Object.<anonymous> (C:\workspace\electron-edge-js-with-electron-builder\release-with-asar\win-unpacked\resources\app.asar\main.js:6:29)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Object.<anonymous> (C:\workspace\electron-edge-js-with-electron-builder\release-with-asar\win-unpacked\resources\electron.asar\browser\init.js:181:12)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32) {
  Message: 'Die Datei oder Assembly ' +
    '"file:///C:\\workspace\\electron-edge-js-with-electron-builder\\release-with-asar\\win-unpacked\\resources\\app.asar\\node_modules\\edge-cs\\lib\\edge-cs.dll" ' +
    'oder eine Abh├ñngigkeit davon wurde nicht gefunden. Das System kann ' +
    'die angegebene Datei nicht finden.',
  FileName: 'file:///C:\\workspace\\electron-edge-js-with-electron-builder\\release-with-asar\\win-unpacked\\resources\\app.asar\\node_modules\\edge-cs\\lib\\edge-cs.dll',
  FusionLog: 'WRN: Protokollierung der Assemblybindung ist AUS.\r' +
    '\nSie k├Ânnen die Protokollierung der Assemblybindungsfehler ' +
    'aktivieren, indem Sie den Registrierungswert ' +
    '[HKLM\\Software\\Microsoft\\Fusion!EnableLog] (DWORD) auf 1 ' +
    'festlegen.\r' +
    '\nHinweis: Die Protokollierung der Assemblybindungsfehler f├╝hrt zu ' +
    'einer gewissen Leistungseinbu├ƒe.\r' +
    '\nSie k├Ânnen dieses Feature deaktivieren, indem Sie den ' +
    'Registrierungswert [HKLM\\Software\\Microsoft\\Fusion!EnableLog] ' +
    'entfernen.\r' +
    '\n',
  Data: {},
  InnerException: null,
  TargetSite: {},
  StackTrace: '   bei System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, ' +
    'String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, ' +
    'StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean ' +
    'throwOnFileNotFound, Boolean forIntrospection, Boolean ' +
    'suppressSecurityChecks)\r' +
    '\n   bei ' +
    'System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName ' +
    'assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, ' +
    'StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean ' +
    'throwOnFileNotFound, Boolean forIntrospection, Boolean ' +
    'suppressSecurityChecks)\r' +
    '\n   bei System.Reflection.RuntimeAssembly.InternalLoadFrom(String ' +
    'assemblyFile, Evidence securityEvidence, Byte[] hashValue, ' +
    'AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean ' +
    'suppressSecurityChecks, StackCrawlMark& stackMark)\r' +
    '\n   bei System.Reflection.Assembly.UnsafeLoadFrom(String assemblyFile)\r' +
    '\n   bei ClrFunc.Initialize(FunctionCallbackInfo<v8::Value>* info)',
  HelpLink: null,
  Source: 'mscorlib',
  HResult: -2147024894,
  message: 'Die Datei oder Assembly ' +
    '"file:///C:\\workspace\\electron-edge-js-with-electron-builder\\release-with-asar\\win-unpacked\\resources\\app.asar\\node_modules\\edge-cs\\lib\\edge-cs.dll" ' +
    'oder eine Abh├ñngigkeit davon wurde nicht gefunden. Das System kann ' +
    'die angegebene Datei nicht finden.',
  name: 'System.IO.FileNotFoundException'
}
```
My resources directory for the asar variant looks like this:
![resources-with-asar](https://user-images.githubusercontent.com/45351461/65769223-5ceb0a80-e133-11e9-9c36-d3ca93d3ca11.jpg)

Any help would be welcome!

**Comment by HaraldStiwa** [comment]
Using `"asar": false` is (as seen above) a work-around for me, but not a solution, as electron-builder indicates in its output: `• asar using is disabled — it is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available`. But the files that have to be unpacked are already unpacked. The problem is that somehow electron-edge-js or some of its libraries is searching in the wrong path.

**Comment by Hammster** [comment]
Native Node Addons are not supposed to be loaded from `.asar` 

You can take this information from the Electron Docs:
https://electronjs.org/docs/tutorial/application-packaging#extra-unpacking-on-some-apis

You have not configured `electron-builder` correctly, you can exclude specific files via your config. but this has nothing to do with `electron-edge-js`

**Comment by HaraldStiwa** [comment]
Well, as you can maybe see in the second screenshot, electron-builder automatically detects these modules and is saving them (unpacked) into resources\app.asar.unpacked but electron-edge-js is using the wrong path and wants to load them from the asar-archive.

**Comment by AbbetWang** [comment]
@HaraldStiwa  Thanks first, how to solve this finally.
