### ISSUE TITLE
Electron 7

### ISSUE THREAD

**Issue by erik-kallen** [agracio/electron-edge-js#69]
Hi, and thanks for this great project!

Support for Electron 7 would be nice. It should be node 12.8.1, but there might be some issue because when I tried building edge-js for that node version, I got errors saying "The specified procedure could not be found." when trying to load the module. But that is probably something I did wrong because I am not experienced building node native modules

**Comment by misbeliever** [comment]
Wondering if there plans to add support for Electron v7?

**Comment by yongjias** [comment]
second this proposal

**Comment by uzumakinaruto123** [comment]
Any workaround you guys tried until we get the update?

**Comment by misbeliever** [comment]
> Any workaround you guys tried until we get the update?

https://github.com/agracio/electron-edge-js/pull/71 works

**Comment by Hammster** [comment]
You can also build electron-edge-js manually 

Switch out `YOUR_ELECTRON_VERSION` and `ABSOLUTE_PATH_TO_EDGE_JS`

`node-gyp rebuild --msvs_version=2019 --target=YOUR_ELECTRON_VERSION --arch=x64 --dist-url=https://electronjs.org/headers --arch=x64 --directory=ABSOLUTE_PATH_TO_EDGE_JS`

**Comment by aalvarez255** [comment]
@Hammster Could you help me with the manual build please? Not working for now :/

These are the steps I followed:

1. Clone electron-edge-js source code.
2. Execute the command `node-gyp rebuild --msvs_version=2019 --target=7.1.2 --arch=ia32 --dist-url=https://electronjs.org/headers --arch=ia32 --directory=C:\electron-edge-js`.
3. Copy generated file `edge_coreclr.node` to my electron project root.

Then, I try to use the module:

`const edge = window.require('./edge_coreclr.node')`
`const func= edge.func({ ... })`

But I'm getting the following error `edge.func is not a function`.
Did I do something wrong?

Thanks :)

**Comment by gdavidkov** [comment]
@aalvarez255 I made a pull request. You can clone it and link it to your project.

**Comment by Hammster** [comment]
@aalvarez255 you don't need to copy the `.node` file :) Once you installed the package you simply run the command i've send and it should work out of the box.

The reason why it says `edge.func` is not a function is because it misses the JS code from `electron-edge-js` :)

**Comment by uzumakinaruto123** [comment]
@gdavidkov  I just installed using your git repo URL. works for now. npm install https://github.com/gdavidkov/electron-edge-js

**Comment by GuoSirius** [comment]
> Hi, and thanks for this great project!
> 
> Support for Electron 7 would be nice. It should be node 12.8.1, but there might be some issue because when I tried building edge-js for that node version, I got errors saying "The specified procedure could not be found." when trying to load the module. But that is probably something I did wrong because I am not experienced building node native modules

Node@12.14.0 not supported

**Comment by agracio** [comment]
https://github.com/agracio/electron-edge-js/pull/71 with support for Electron 7 was merged and released 2 weeks ago.
