### ISSUE TITLE
ELectron-Edge-Js and .net standard 2.0 compatibility issue

### ISSUE THREAD

**Issue by bnlakshmibn** [agracio/electron-edge-js#7]
Hi,

I have created a sample electron app and installed electron-edge-js package. Tried to add a .net framework class library dll and called a method from it. It worked fine.

But the issue is, I tried to create a .net standard 2.0 class library and referenced that dll in my app and tried calling a method from that (a method which simply returns a string). But I got the error " 'Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.'"

Please help me out to find a solution since the project is critical.

Thanks in advance

**Comment by bnlakshmibn** [comment]
Any solution? Anyone?

**Comment by bnlakshmibn** [comment]
Got the solution. I have added what all dlls needed for .net standard 2.0 to run, in to my app folder. Issue resolved.

**Comment by grofit** [comment]
@bnlakshmibn Do you mean you just included all the assemblies required in your dependency chain or did you have to do anything else?
