### ISSUE TITLE
Reference 32bit C# DLL in 64bit workstation

### ISSUE THREAD

**Issue by JohnyHHH** [agracio/electron-edge-js#72]
I'm using electron-edge-js to integrate my 32bit C# dll into electron app project which develop in 64bit environment. 

This return error 
"Could not load file or assembly 'My32Bit.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format."

Is there anything i need to configure?
I'm new to node.js and electron app.
thanks..

**Comment by agracio** [comment]
This is a typical .NET error for mismatching architecture not something specific to `electron-edge-js`, you should start by creating a working .NET project using your dlls and a console as test then adding it to 32 bit Electron.
