### ISSUE TITLE
Electron 8

### ISSUE THREAD

**Issue by camhart** [agracio/electron-edge-js#77]
Needs updated for electron 8.

I love electron-edge.  Thanks for all you do.

**Comment by Hammster** [comment]
#76 fixes this

**Comment by surajbabar** [comment]
When will this change be released?
We have upgraded electron version to 8, but only due to this package we are downgrading it to 7. 
It will help us a lot if you release this change soon.

Thanks for writing this awesome package !

**Comment by Hammster** [comment]
@agracio has to accept the pull request #76 or you can download the package from the fork where the PR has been written by getting it from git directly.

In your package.json
`"electron-edge-js": "gdavidkov/electron-edge-js"`

**Comment by agracio** [comment]
https://github.com/agracio/electron-edge-js/pull/76 is now merged and published to npm.
