### ISSUE TITLE
Do I have to install .net framework on the client's computer?

### ISSUE THREAD

**Issue by zwdgit** [agracio/electron-edge-js#78]

**Comment by camhart** [comment]
Yes.  It'll need .net 4.5 I believe--which Windows 8 and above ships with.  Windows 7 users may need to install .net 4.5.

https://docs.microsoft.com/en-us/archive/blogs/astebner/mailbag-what-version-of-the-net-framework-is-included-in-what-version-of-the-os

(I'm not an authoritative answer on this--just based off https://github.com/tjanczuk/edge).

**Comment by agracio** [comment]
You only need local .NET Framework install if you using .NET Framewrok specifically. When using .NET Core you can distribute a self contained app that would include all required assemblies.
You need to specify the following in your .csproj
```
 <PreserveCompilationContext>true</PreserveCompilationContext>
 <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
```
