### ISSUE TITLE
Need electron-edge-js 8.3.0 but in releases its showing version 8.2.2

### ISSUE THREAD

**Issue by glyse** [agracio/electron-edge-js#8]
Hi,

Actually I want to use electron-edge-js 8.3.0 source code, but in releases its showing only 8.2.2.
https://github.com/agracio/electron-edge-js/releases 

Could you please add the latest release (8.3.0) in the release tab please?

Regards
Glyse

**Comment by agracio** [comment]
Not sure what you mean by that, there is no `electron-edge-js` 8.3.0

**Comment by glyse** [comment]
I requested my organisation to add electron-edge-js@8.3.0  to their npm repository. So they are referring the source code from https://github.com/agracio/electron-edge-js/releases and its miss matching with electron-edge-js@8.2.2. So they rejected my request because the requested version not available in the latest release list. 

I am able to install electron-edge-js@8.3.0 from npm, but as per organization rule it should be install through their npm repository. So thats why I asked if possible please add the latest release details in the release page with latest source code zip file.

Thanks for your help
Glyse

**Comment by agracio** [comment]
I do not actually intend to publish releases for this repo, regardless of version as I do not see it serving any purpose. This is a public repo and source code can be downloaded directly.
I have removed releases completely now.
There are many npm packages that have no _releases_ on Github, and i think this should be one of them.

**Comment by agracio** [comment]
Let me know if removing releases completely solves your problem
