### ISSUE TITLE
Electron builder - ia32 dll's included

### ISSUE THREAD

**Issue by camhart** [agracio/electron-edge-js#80]
When building an installer using electron-builder that's only for x64, the ia32 (I assume 32 bit) dll's are included.  Is that necessary?

If it's not necessary, would that be something fixed here or on electron-builders side?

**Comment by agracio** [comment]
`electron-edge-js` had no way of knowing what you need to package. You should specify all your requirements on `electron-builder` side. I am pretty sure its consistent with any other project where you want to try and trim down the included content.
