### ISSUE TITLE
Usage with node 12.16.2

### ISSUE THREAD

**Issue by godiaz89** [agracio/electron-edge-js#81]
Iam using node version 12.16.2 and electron 8.2.4.
![image](https://user-images.githubusercontent.com/40272321/80745508-ca5e7f80-8af6-11ea-8b67-a57f9bf88c18.png)
![image](https://user-images.githubusercontent.com/40272321/80745562-dba78c00-8af6-11ea-96bc-5cc3a471debb.png)

When running  a test script with edge I am getting the following error:
![image](https://user-images.githubusercontent.com/40272321/80744922-c9791e00-8af5-11ea-95a3-1fb022d0d503.png)

does this means I have to re build edge for this version of node? considering that the readme page for electron-edge-js shows that  support is up to the 12.13 node version.
Or does this error means something else is not working?
Im calling the edge function inside my electron main process

```
const { app, BrowserWindow, ipcMain } = require('electron')
const path = require('path');
const isDev= require('electron-is-dev');
const fs = require('fs');
const {promisify} = require('util')
const edge = require('edge-js')

function createWindow () {
  // Crea la ventana del navegador.
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      contextIsolation:true,
      enableRemoteModule:false,
      preload:path.join(__dirname,"preload.js")
    }
  })
  // and load the index.html of the app.
//   win.loadFile('index.html')
win.loadURL(isDev?'http://localhost:3000':`file://${path.join(__dirname,'../build/index.html')}`);

//....

var createHello = edge.func(function () {/*
  async (input) =>
  {
      return (Func<object,Task<object>>)(async (i) => { 
          Console.WriteLine("Hello from .NET"); 
          return null; 
      });
  }
*/});

var hello = createHello(null, true); 
hello(null, true); // prints out "Hello from .NET"
```

**Comment by andyTsing** [comment]
const edge = require('edge-js')
should is 
const edge = require('electron-edge-js ')
maybe help u

**Comment by godiaz89** [comment]
> const edge = require('edge-js')
> should is
> const edge = require('electron-edge-js ')
> maybe help u

Thanks a lot, I used the 'electron-edge-js' module and rebuilded the module using the 'BuildAll.bat' script. After that it works perfectly!
