### ISSUE TITLE
electron 9 support

### ISSUE THREAD

**Issue by camhart** [agracio/electron-edge-js#83]
What's needed in order to add support for electron 9?

**Comment by paulooliveirapd** [comment]
@agracio, I would also like to know that. Researching, I found a way to compile this library for electron 9, but I had problems every time I tried. Maybe if you or @gdavidkov have a step-by-step guide to do this, i am willing to compile and open a pull request for it.

**Comment by gdavidkov** [comment]
Here is the [PR](https://github.com/agracio/electron-edge-js/pull/84).
@paulooliveirapd  You can check my PR for reference.

**Comment by paulooliveirapd** [comment]
@gdavidkov, Thank you very much.
When i tried to do this, i couldn't generate those .dll and .node files.
Is there any script to do this?

**Comment by gdavidkov** [comment]
@paulooliveirapd In the repo, there is a folder with name tools. From inside you can run build.bat with the following arguments (build.bat release 12.14.1) and the script will do everything that you need :)

**Comment by paulooliveirapd** [comment]
Thank you.

**Comment by agracio** [comment]
Released. @gdavidkov thank you for compiling binaries.
