### ISSUE TITLE
TypeError: edge.initializeClrFunc is not a function

### ISSUE THREAD

**Issue by jjustin3** [agracio/electron-edge-js#88]
I know that this issue has been covered before both here and in the `edge-js` repository as well, but I am running into this issue _only_ when using `dotnet publish` targeting a .NET Core application. This is also reproduceable within the `electron-edge-js-quick-start` repo if you were to use `dotnet publish path/to/proj -c Release --self-contained -r win-x64` instead of the default `dotnet build` command.

My current setup is as follows:
* electron: v9.0.4
* node: v12.14.1
* electron-edge-js: v12.14.2
* platform: win32

I am creating this as a self-contained application but it appears that the `edgeNative` value/module is not properly loading even though this resolves to `C:\Users\path\to\project\node_modules\electron-edge-js\lib\native\win32\x64\12.14.1\edge_coreclr`. Additionally, my `process.env.EDGE_APP_ROOT` resolves to the correct value, I have `EdgeJs.dll` in this directory, and I have properly set `process.env.EDGE_USE_CORECLR`. Finally, as per [this comment](https://github.com/agracio/electron-edge-js-quick-start/issues/5#issuecomment-479075289), I have also set `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` within my .csproj.

The last bit of context I can provide is that, when enabling tracing, many of the libraries detailed within the .deps.json of the output .NET Core project are evaluated and produce results similar to the following:
```
Reconciling library System.IO.FileSystem/4.0.1
Library System.IO.FileSystem/4.0.1 does not exist
```
Note that this is not specific to System.IO.FileSystem, but nearly every single item that was detailed after adding in the CopyLocalLockFileAssemblies property to the .csproj. This also occurs regardless the .NET Core version.

Any help or information would be appreciated. I've been banging my head against the desk for a couple of days now and can't seem to get my application working as a standalone published library.

**Comment by saiponnada** [comment]
Hey, I am facing similar issue as well. Were you able to find the solution ?

**Comment by arsenikstiger** [comment]
Hi,
Same question as @saiponnada, how did you manage this (if you did) ?

**Comment by saiponnada** [comment]
> Hi,
> Same question as @saiponnada, how did you manage this (if you did) ?

We didn't yet. We thought of moving away from the library totally.

**Comment by vineetmimrot** [comment]
@saiponnada What are you using now then?

**Comment by Once-Man** [comment]
TypeError: edge.global is not a function
