### ISSUE TITLE
EDGE_USE_CORECLR doesn't work properly

### ISSUE THREAD

**Issue by smx-smx** [agracio/electron-edge-js#9]
```builtEdge = path.resolve(__dirname, '../build/Release/' + (process.env.EDGE_USE_CORECLR || !fs.existsSync(path.resolve(__dirname, '../build/Release/edge_nativeclr.node')) ? 'edge_coreclr.node' : 'edge_nativeclr.node'));```

This comparison is failing for some reason, here's the debug i did

```javascript
var check1 = ((process.env.EDGE_USE_CORECLR || !fs.existsSync(path.resolve(__dirname, '../build/Release/edge_nativeclr.node'))) ? 'edge_coreclr.node' : 'edge_nativeclr.node');
var check2 = !fs.existsSync(path.resolve(__dirname, '../build/Release/edge_nativeclr.node'));
var check3 = !fs.existsSync(path.resolve(__dirname, '../build/Release/edge_nativeclr.node')) ? 'edge_coreclr.node' : 'edge_nativeclr.node';
console.log(
    path.resolve(__dirname, '../build/Release/edge_nativeclr.node'), //<fullPath>\build\Release\edge_nativeclr.node
    process.env.EDGE_USE_CORECLR, //false
    check1, //edge_coreclr.node <-- problem
    check2, //false
    check3 //edge_nativeclr.node
);
```

I'm trying to use .NET on Windows but CoreCLR gets used every time due to the failing check

**Comment by smx-smx** [comment]
I might have found out why, i think process.env.EDGE_USE_CORECLR only checks for the existance of the environment variable, so changing the lefthand part of the or check with `process.env.EDGE_USE_CORECLR === true` fixes it

**Comment by agracio** [comment]
This is likely a problem with your custom build of `electron-edge-js`. Normally you would not have `../build` directory unless you performed a build yourself. I would advise you to simply delete `build`.

**Comment by smx-smx** [comment]
Yes it's correct, i build edge myself (i have it automated in my npm install sequence since the old edge when it wasn't being updated for new electron builds). Nontheless, this is a problem and shouldn't be happening

**Comment by agracio** [comment]
From my experience having `../build` directory present without a need for it can cause problems, especially when different node versions are involved.

**Comment by smx-smx** [comment]
I removed the build directory, it still picks CoreCLR due to the check being present down below in the same syntax
```javascript
else if (process.platform === 'win32') {
    edgeNative = path.resolve(__dirname, './native/' + process.platform + '/' + process.arch + '/' + determineVersion() + '/' + (process.env.EDGE_USE_CORECLR ? 'edge_coreclr' : 'edge_nativeclr'));
}
```

**Comment by agracio** [comment]
This means that something is setting `process.env.EDGE_USE_CORECLR` variable either in your code or environment. Check that you don't have some kind of forgotten code somewhere or an environmental variable.

**Comment by smx-smx** [comment]
I was setting it to false, but i just removed it and now it works.
I'm not too sure that's how it's supposed to work, because if i see "EDGE_USE_CORECLR" in the examples i expect it to **NOT** use it if i set it to false

**Comment by agracio** [comment]
On typescript side you should be able to do `process.env['EDGE_USE_CORECLR'] = 0` unless you have set specific typescript restrictions.

**Comment by smx-smx** [comment]
it's not possible, process.env is declared as expecting string types only

from the typings:
```typescript
export interface ProcessEnv {
        [key: string]: string | undefined;
    }

env: ProcessEnv;
```

**Comment by smx-smx** [comment]
The issue is that process.env values get converted to strings when something is written to it, so you have to tread them as strings

```
> process.env.EDGE_USE_CORECLR = 0
0
> process.env.EDGE_USE_CORECLR
'0'
```
