### ISSUE TITLE
What dll's are necessary?

### ISSUE THREAD

**Issue by camhart** [agracio/electron-edge-js#91]
If I'm shipping my electron app using electron-edge-js v 12.14.2, what dll's do I need to include in production builds?

electron-edge-js\lib\native\win32\x64 has, what looks like, a directory for each version of electron-edge-js, as well as 4 dll's in the root directory.  Do I only need to include the 12.14.2 directory?

**Comment by Alatius** [comment]
From my own experimenting, it seems so. Saves quite a lot of space to exclude the rest!
