### ISSUE TITLE
How to call a constructor with parameters

### ISSUE THREAD

**Issue by Navakanth009** [agracio/electron-edge-js#93]
Lets say I have class in C# like below

namespace Test
{
public class Greetings
{
public Greetings(String greet) {
Greet = name;
}
public async Task Greet()
{
return String.Format("On {0}, you said {1}",
System.DateTime.Now,
Greet);
}
}
}

I build this as project and I am trying to access the Greetings.Greet() from .dll like below

let assemblyFile = "./Test.dll"
const init = edge.func({
assemblyFile : assemblyFile,
typeName: 'Test.Greetings',
methodName: 'Greet'
});

How to call the Greetings() constructor with parameters here.

**Comment by alencarandre** [comment]
You can try it


```js
import edge from "electron-edge-js";

const testFunc = edge.func({
  source: function() {
    /*
      async (dynamic params) =>
      {
        new Namespace.Klass(params.constructorParamOne, params.constructorParamTwo).Method(params.one, params.two);
      }
    */
  },
  references: ["Module.dll"],
});

const params = {
  constructorParamOne: 'value one',
  constructorParamTwo: true,
  one: 1,
  two: 2
}

testFunc(params, function(error, result) {
  if (error) throw error;
  return result;
});
```
