### ISSUE TITLE
Error: Cannot find module ....\dist_electron\native\win32\x64\12.16.3\edge_nativeclr

### ISSUE THREAD

**Issue by janosvajda** [agracio/electron-edge-js#98]
Hi,

I use Electron 10 and Node.js v12.16.3 under Windows 10. I wanted to just test this project. I could install it. 

When I try to test it just locally it shows me this error message:

App threw an error during load
`Error: Cannot find module 'C:\Users\testuser\projects\projectname\dist_electron\native\win32\x64\12.16.3\edge_nativeclr'
`

I use Vue CLI Plugin Electron Builder and I tried to add the project's vue.config.js file these lines:

```
pluginOptions: {
    electronBuilder: {
      externals: ["electron-edge-js"],
```

But, unfortunately, It did not help. 

I followed all instructions on electron-edge-js GitHub page and just would have liked to run this test script:

```
var edge = require('electron-edge-js');
var helloWorld = edge.func(function () {/*
    async (input) => {
        return ".NET Welcomes " + input.ToString();
    }
*/});
```

This might not be an issue, it might be caused by a lack of documentation? I do not know.

Thank you if someone can fix/update the documentation or just have any idea.

Thanks.

**Comment by PrexCoder** [comment]
Same problem here, did anyone manage to solve this?

**Comment by agracio** [comment]
Take a look at https://github.com/agracio/electron-edge-js/issues/74
